name: main
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  workflow_dispatch:
    inputs:
      run_mypy_only:
        type: boolean
        default: true
        description: "Is manually run"


jobs:
  multilabeler:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    if: github.event_name == 'pull_request_target'

    steps:
      - name: data
        run: |
          env
          echo $github.event_name
          echo ${{ github.event_name }}
          echo "${{ github.event_name }}"
          echo "${{ github.event_name }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - uses: fuxingloh/multi-labeler@v4
