name: main
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  workflow_dispatch:
    inputs:
      run_mypy_only:
        type: boolean
        default: true
        description: "Is manually run"


jobs:
#  release_drafter:
#    runs-on: ubuntu-22.04
#    permissions:
#      contents: write
#      pull-requests: write
##    env:
##      GH_TOKEN: ${{ github.token }}
##      OWNER: ${{ github.repository_owner }}
##      REPO: ${{ github.event.repository.name }}
#    steps:
#      - name: print data
#        run: |
#          echo ${{ secrets.GITHUB_TOKEN }}
#          echo {{ secrets.GITHUB_TOKEN }}
#          echo ${{ github.token }}
#          echo {{ github.token }}
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - uses: release-drafter/release-drafter@v6
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add_labels:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write
#    env:
#      GH_TOKEN: ${{ github.token }}
#      OWNER: ${{ github.repository_owner }}
#      REPO: ${{ github.event.repository.name }}
    if: github.event_name == 'pull_request_target'

    steps:
      - name: data
        run: |
          env
          echo $github.event_name
          echo ${{ github.event_name }}
          echo "${{ github.event_name }}"
          echo "${{ github.event_name }}"

      - name: Get labels to add from PR
        id: get_labels
        working-directory: .github/.scripts
        run: echo "labels=$(./add_labels.sh $PR_TITLE)" >> $GITHUB_OUTPUT
        env:
          PR_TITLE: ${{ github.event.pull_request.title }

      - name: Echo labels to add
        run: | 
          echo ${{ steps.get_labels.outputs.labels }}

      - name: Checkout code
        uses: actions/checkout@v4

#      - uses: fuxingloh/multi-labeler@v4
