name: main
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
      - labeled
      - unlabeled
  workflow_dispatch:
    inputs:
      run_mypy_only:
        type: boolean
        default: true
        description: "Is manually run"


jobs:
#  release_drafter:
#    runs-on: ubuntu-22.04
#    permissions:
#      contents: write
#      pull-requests: write
##    env:
##      GH_TOKEN: ${{ github.token }}
##      OWNER: ${{ github.repository_owner }}
##      REPO: ${{ github.event.repository.name }}
#    steps:
#      - name: print data
#        run: |
#          echo ${{ secrets.GITHUB_TOKEN }}
#          echo {{ secrets.GITHUB_TOKEN }}
#          echo ${{ github.token }}
#          echo {{ github.token }}
#      - name: Checkout code
#        uses: actions/checkout@v4
#      - uses: release-drafter/release-drafter@v6
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  add_labels:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    if: github.event_name == 'pull_request_target'

    steps:
      - name: data
        run: |
          echo ${{ github.repository_owner }}
          echo ${{ github.event.repository.name }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get labels to add from PR
        working-directory: .github/.scripts
        run: ./add_labels.sh
        env:
          REPO: ${{ github.event.pull_request.head.repo.full_name }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          GH_TOKEN: ${{ github.token }}


#      - uses: fuxingloh/multi-labeler@v4
